/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.cadenas.telcel;

/**
 *
 * @author consultor006
 */
public class Cadenas {

    public static void main(String[] args) {

        String cadInburo ="		<SolicitudProvider>\n" +
"			<TipoSolicitud>repoAU</TipoSolicitud> \n" +
"			<Solicitud> \n" +
"			<Header> \n" +
"			<HoraEntrada>20160416182044</HoraEntrada> \n" +
"			<Ip>192.9.198.108</Ip> \n" +
"			<Usuario>SISACT R9</Usuario>\n" +
"            <IdSistema>SISACT</IdSistema>\n" +
"			<Folio>CEX16041618204499744\n" +
"			</Folio>\n" +
"			<Historico>180</Historico> \n" +
"			</Header>\n" +
"			<Segmentos>\n" +
"			<Autenticacion> \n" +
"				<lis_tipo_reporte>RCN</lis_tipo_reporte>\n" +
"				<lis_tipo_salida>1</lis_tipo_salida>\n" +
"				<lis_referencia_operador>NUM REFERNCIA OPERADOR R9</lis_referencia_operador> \n" +
"				<lis_cuenta_con_tc>V</lis_cuenta_con_tc>\n" +
"				<lis_ultimos_digitos>4118</lis_ultimos_digitos> \n" +
"				<lis_cred_hipoteca_banco>F</lis_cred_hipoteca_banco> \n" +
"				<lis_credito_automotriz>F</lis_credito_automotriz> \n" +
"			</Autenticacion>            \n" +
"			<EncabezadoINTL> \n" +
"				<lis_referencia_operador>NUM REFERNCIA OPERADOR R9</lis_referencia_operador>\n" +
"				<ProductoRequerido>001</ProductoRequerido> \n" +
"				<ls_usr>REPOBCR09</ls_usr> \n" +
"				<ls_pass>XXXXXXXX</ls_pass> \n" +
"				<adm_intl_tipo_cta>I</adm_intl_tipo_cta> \n" +
"				<adm_intl_tipo_contrato>CC</adm_intl_tipo_contrato> \n" +
"				<adm_intl_unidadmonetaria>MX</adm_intl_unidadmonetaria>\n" +
"				<adm_intl_imp_contrato>000000000</adm_intl_imp_contrato> \n" +
"				<adm_intl_idioma>SP</adm_intl_idioma> \n" +
"			</EncabezadoINTL>\n" +
"			<Nombre> \n" +
"				<lv_ape_pat>CASAS</lv_ape_pat> \n" +
"				<lv_ape_mat>RAMOS</lv_ape_mat>\n" +
"				<lv_prim_nom>JOAQUIN</lv_prim_nom> \n" +
"				<lv_seg_nom>ALONSO</lv_seg_nom> \n" +
"				<lv_fec_nac>23101995</lv_fec_nac> \n" +
"				<lv_rfc>CARJ951023000</lv_rfc> \n" +
"				<lis_sexo>M</lis_sexo> \n" +
"			</Nombre> 			\n" +
"			<Direccion>\n" +
"				<lis_direccion1>DE MELESIO MARQUEZ S/N</lis_direccion1> \n" +
"				<lis_direccion2>0</lis_direccion2> \n" +
"				<lis_colonia_poblacion>SAN ANDRES JALTENCO</lis_colonia_poblacion>\n" +
"				<lis_delegacion_municipio>JALTENCO</lis_delegacion_municipio> \n" +
"				<lis_ciudad>JALTENCO</lis_ciudad> \n" +
"				<lis_estado>EM</lis_estado> \n" +
"				<lis_cp>55780</lis_cp> \n" +
"			</Direccion>			\n" +
"            </Segmentos>\n" +
"			    </Solicitud> \n" +
"        </SolicitudProvider>";
        
        
        
        
        
        
        
        
        
        
        String cadBuro ="<ProviderData> <TipoSolicitud>idProv</TipoSolicitud>\n" +
"            <ResponseProvider> <Header>\n" +
"            <HoraRespuestaSalida>09052018094138</HoraRespuestaSalida>\n" +
"            <Folio>CEX20180509094192055</Folio> </Header> <Autenticado> <ReporteDeCredito> <EncabezadoResponseINTL> <v_version>11</v_version> \n" +
"            <lis_referencia_operador>CEX20180509094192055</lis_referencia_operador><v_pais>MX</v_pais> <v_buro>0000</v_buro> <v_cve_otorga>UT98002491</v_cve_otorga>\n" +
"            <v_cve_retorno_p>1</v_cve_retorno_p><v_cve_retorno_s>0</v_cve_retorno_s> </EncabezadoResponseINTL> <Nombre> <lv_ape_pat>CARRILLO</lv_ape_pat> <lv_ape_mat>RODRIGUEZ</lv_ape_mat>\n" +
"            <lv_prim_nom>LUIS</lv_prim_nom> <lv_seg_nom>ANGEL</lv_seg_nom> <lv_fec_nac>29041998</lv_fec_nac> <lv_rfc>CARL980429</lv_rfc> <lis_nacionalidad>MX</lis_nacionalidad>\n" +
"            <lis_estado_civil>D</lis_estado_civil> <lis_sexo>F</lis_sexo> </Nombre> <DireccionesReportadas> <Direccion> <lis_direccion1>CDA RIO BRAVO MZ67</lis_direccion1> \n" +
"            <lis_colonia_poblacion>EL SALADO</lis_colonia_poblacion> <lis_delegacion_municipio>LA PAZ</lis_delegacion_municipio> <lis_ciudad>LA PAZ</lis_ciudad> <lis_estado>EM</lis_estado>\n" +
"             <lis_cp>56524</lis_cp> <lis_tipo_domicilio>H</lis_tipo_domicilio><lis_indicador_esp_domicilio>K</lis_indicador_esp_domicilio><FechaDeReporteDeLaDireccion>07082017</FechaDeReporteDeLaDireccion>\n" +
"            </Direccion> </DireccionesReportadas> <ConsultasReportadas> <ConsultasEfectuadas> <v_consulta>09052018</v_consulta> <v_cve_otorga>UT98002491</v_cve_otorga><v_nom_otorga>TELCEL</v_nom_otorga>\n" +
"             <v_cve_t_contr>CC</v_cve_t_contr> <v_importe_cont>0</v_importe_cont> <v_cve_respon>I</v_cve_respon> </ConsultasEfectuadas> <ConsultasEfectuadas> <v_consulta>20042018</v_consulta>\n" +
"            <v_nom_otorga>SIC</v_nom_otorga> <v_cve_t_contr>CL</v_cve_t_contr> <v_importe_cont>0</v_importe_cont><v_cve_respon>I</v_cve_respon> </ConsultasEfectuadas>\n" +
"             <ConsultasEfectuadas> <v_consulta>07082017</v_consulta> <v_nom_otorga>SIC</v_nom_otorga> <v_cve_t_contr>UK</v_cve_t_contr> <v_importe_cont>0</v_importe_cont> <v_cve_respon>I</v_cve_respon>\n" +
"            <v_indica_con_n>Y</v_indica_con_n> </ConsultasEfectuadas> </ConsultasReportadas> <ReportesRealizados> <ResumenReporte> <v_ingre_bd>07082017</v_ingre_bd> <v_mop_07>00</v_mop_07>\n" +
"            <v_mop_06>00</v_mop_06> <v_mop_05>00</v_mop_05> <v_mop_04>00</v_mop_04> <v_mop_03>00</v_mop_03> <v_mop_02>00</v_mop_02> <v_mop_01>00</v_mop_01> <v_mop_00>00</v_mop_00> \n" +
"            <v_mop_ur>00</v_mop_ur> <v_n_cuenta>0000</v_n_cuenta> <v_n_pago_f>0000</v_n_pago_f> <v_n_cta_ra>0000</v_n_cta_ra> <v_n_cta_cerr>0000</v_n_cta_cerr> <v_n_cta_neg>0000</v_n_cta_neg> \n" +
"            <v_n_ctas_mop>0000</v_n_ctas_mop> <v_n_cta_disp>00</v_n_cta_disp> <v_n_sol_6_mes>01</v_n_sol_6_mes> <v_u_dirr>N</v_u_dirr> <v_msg_allert>NNNNN</v_msg_allert><v_declara>N</v_declara>\n" +
"            <v_mop_96>00</v_mop_96> <v_mop_97>00</v_mop_97> <v_mop_99>00</v_mop_99> <v_open_cta_ant>00000000</v_open_cta_ant><v_open_cta_rec>00000000</v_open_cta_rec> <v_n_t_repo>02</v_n_t_repo>\n" +
"            <v_n_t_repo_rec>20042018</v_n_t_repo_rec><v_n_t_cta_des_cob>00</v_n_t_cta_des_cob><v_open_cc>00000000</v_open_cc> <v_n_sol_cc>00</v_n_sol_cc>\n" +
"             <v_sol_cc>00000000</v_sol_cc> </ResumenReporte> </ReportesRealizados> <Fin> <v_long>00622</v_long> <v_ctrl_consul>1560584231</v_ctrl_consul>\n" +
"            <v_chr_fin>0102</v_chr_fin> </Fin> </ReporteDeCredito> </Autenticado> </ResponseProvider> </ProviderData>";
        
                
        String repoIccIn = "<reporteBcIccWSBean>\n"
                + "	<controlData>\n"
                + "		<messageUUID>BCSERVICES-PF-LOCAL-0001</messageUUID>\n"
                + "		<requestDate>2018-09-04T11:53:55.044-05:00</requestDate>\n"
                + "		<sendBy>CLIENT</sendBy>\n"
                + "		<version>1</version>\n"
                + "	</controlData>\n"
                + "	<peticion>\n"
                + "		<solicitud>\n"
                + "			<header>\n"
                + "				<folio>CCS18090411535592526</folio>\n"
                + "				<historico>0</historico>\n"
                + "				<horaEntrada>20180904115355</horaEntrada>\n"
                + "				<idSistema>DEUR</idSistema>\n"
                + "				<ip>191.9.6.18</ip>\n"
                + "				<usuario>DEUR</usuario>\n"
                + "			</header>\n"
                + "			<segmentos>\n"
                + "				<autenticacion>\n"
                + "					<lis_cred_hipoteca_banco>F</lis_cred_hipoteca_banco>\n"
                + "					<lis_credito_automotriz>F</lis_credito_automotriz>\n"
                + "					<lis_cuenta_con_tc>V</lis_cuenta_con_tc>\n"
                + "					<lis_referencia_operador>CCS1809041153559I00002526</lis_referencia_operador>\n"
                + "					<lis_tipo_reporte>RCN</lis_tipo_reporte>\n"
                + "					<lis_tipo_salida>1</lis_tipo_salida>\n"
                + "					<lis_ultimos_digitos>6165</lis_ultimos_digitos>\n"
                + "				</autenticacion>\n"
                + "				<direccion>\n"
                + "					<lis_ciudad>LA MAGDALENA CONTRERAS</lis_ciudad>\n"
                + "					<lis_cp>10580</lis_cp>\n"
                + "					<lis_delegacion_municipio>LA MAGDALENA CONTRERAS</lis_delegacion_municipio>\n"
                + "					<lis_direccion1>ALDAMA 68</lis_direccion1>\n"
                + "					<lis_estado />\n"
                + "				</direccion>\n"
                + "				<encabezadoINTL>\n"
                + "					<adm_intl_idioma>SP</adm_intl_idioma>\n"
                + "					<adm_intl_imp_contrato>000000000</adm_intl_imp_contrato>\n"
                + "					<adm_intl_tipo_contrato />\n"
                + "					<adm_intl_tipo_cta>I</adm_intl_tipo_cta>\n"
                + "					<adm_intl_unidadmonetaria>MX</adm_intl_unidadmonetaria>\n"
                + "					<lis_referencia_operador>CCS1809041153559I00002526</lis_referencia_operador>\n"
                + "					<ls_pass>hEXSmXfR</ls_pass>\n"
                + "					<ls_usr>ZM98001006</ls_usr>\n"
                + "					<productoRequerido />\n"
                + "				</encabezadoINTL>\n"
                + "				<nombre>\n"
                + "					<lv_ape_mat>GONZALEZ</lv_ape_mat>\n"
                + "					<lv_ape_pat>SANCHEZ</lv_ape_pat>\n"
                + "					<lv_prim_nom>GIL</lv_prim_nom>\n"
                + "					<lv_rfc>SAGG720228000</lv_rfc>\n"
                + "				</nombre>\n"
                + "			</segmentos>\n"
                + "		</solicitud>\n"
                + "		<tipoReporte />\n"
                + "		<tipoSolicitud>repoBC</tipoSolicitud>\n"
                + "	</peticion>\n"
                + "	<controlData2 />\n"
                + "	<detailResponse />\n"
                + "	<respuesta />\n"
                + "</reporteBcIccWSBean>";

        String repoIccOut = "<reporteBcIccWSBean>\n"
                + "	<controlData>\n"
                + "		<messageUUID>BCSERVICES-PF-LOCAL-0001</messageUUID>\n"
                + "		<requestDate>2018-09-04T11:53:55.044-05:00</requestDate>\n"
                + "		<sendBy>CLIENT</sendBy>\n"
                + "		<version>1</version>\n"
                + "	</controlData>\n"
                + "	<peticion>\n"
                + "		<solicitud>\n"
                + "			<header>\n"
                + "				<folio>CCS18090411535592526</folio>\n"
                + "				<historico>0</historico>\n"
                + "				<horaEntrada>20180904115355</horaEntrada>\n"
                + "				<idSistema>DEUR</idSistema>\n"
                + "				<ip>191.9.6.18</ip>\n"
                + "				<usuario>DEUR</usuario>\n"
                + "			</header>\n"
                + "			<segmentos>\n"
                + "				<autenticacion>\n"
                + "					<lis_cred_hipoteca_banco>F</lis_cred_hipoteca_banco>\n"
                + "					<lis_credito_automotriz>F</lis_credito_automotriz>\n"
                + "					<lis_cuenta_con_tc>V</lis_cuenta_con_tc>\n"
                + "					<lis_referencia_operador>CCS1809041153559I00002526\n"
                + "					</lis_referencia_operador>\n"
                + "					<lis_tipo_reporte>RCN</lis_tipo_reporte>\n"
                + "					<lis_tipo_salida>1</lis_tipo_salida>\n"
                + "					<lis_ultimos_digitos>6165</lis_ultimos_digitos>\n"
                + "				</autenticacion>\n"
                + "				<direccion>\n"
                + "					<lis_ciudad>LA MAGDALENA CONTRERAS</lis_ciudad>\n"
                + "					<lis_cp>10580</lis_cp>\n"
                + "					<lis_delegacion_municipio>LA MAGDALENA CONTRERAS\n"
                + "					</lis_delegacion_municipio>\n"
                + "					<lis_direccion1>ALDAMA 68</lis_direccion1>\n"
                + "					<lis_estado />\n"
                + "				</direccion>\n"
                + "				<encabezadoINTL>\n"
                + "					<adm_intl_idioma>SP</adm_intl_idioma>\n"
                + "					<adm_intl_imp_contrato>000000000</adm_intl_imp_contrato>\n"
                + "					<adm_intl_tipo_contrato />\n"
                + "					<adm_intl_tipo_cta>I</adm_intl_tipo_cta>\n"
                + "					<adm_intl_unidadmonetaria>MX</adm_intl_unidadmonetaria>\n"
                + "					<lis_referencia_operador>CCS1809041153559I00002526\n"
                + "					</lis_referencia_operador>\n"
                + "					<ls_pass>hEXSmXfR</ls_pass>\n"
                + "					<ls_usr>ZM98001006</ls_usr>\n"
                + "					<productoRequerido />\n"
                + "				</encabezadoINTL>\n"
                + "				<nombre>\n"
                + "					<lv_ape_mat>GONZALEZ</lv_ape_mat>\n"
                + "					<lv_ape_pat>SANCHEZ</lv_ape_pat>\n"
                + "					<lv_prim_nom>GIL</lv_prim_nom>\n"
                + "					<lv_rfc>SAGG720228000</lv_rfc>\n"
                + "				</nombre>\n"
                + "			</segmentos>\n"
                + "		</solicitud>\n"
                + "		<tipoReporte />\n"
                + "		<tipoSolicitud>repoBC</tipoSolicitud>\n"
                + "	</peticion>\n"
                + "	\n"
                + "	\n"
                + "	<controlData2>\n"
                + "		<value>\n"
                + "			<latency>5244</latency>\n"
                + "			<messageUUID>BCSERVICES-PF-LOCAL-0001</messageUUID>\n"
                + "			<responseDate>2018-09-04T11:52:46.132</responseDate>\n"
                + "			<sendBy>ESB</sendBy>\n"
                + "			<version>1</version>\n"
                + "		</value>\n"
                + "	</controlData2>\n"
                + "	\n"
                + "	<detailResponse>\n"
                + "		<value>\n"
                + "			<actor>IdProviderServices_getIdProvBCSC</actor>\n"
                + "			<businessMeaning>REPORTE EXITOSO</businessMeaning>\n"
                + "			<code>0</code>\n"
                + "			<description>RESPUESTA EXITOSA</description>\n"
                + "			<severityLevel>1</severityLevel>\n"
                + "		</value>\n"
                + "	</detailResponse>\n"
                + "	\n"
                + "	\n"
                + "	\n"
                + "	<respuesta>\n"
                + "		<value>\n"
                + "			<responseProvider>\n"
                + "				<autenticado>\n"
                + "					<reporteDeCredito>\n"
                + "						<consultasReportadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>04092018</v_consulta>\n"
                + "								<v_cve_otorga>ZM98001006</v_cve_otorga>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>TELCEL</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>04042018</v_consulta>\n"
                + "								<v_cve_otorga>UT98002265</v_cve_otorga>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>2000</v_importe_cont>\n"
                + "								<v_nom_otorga>TELCEL</v_nom_otorga>\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>01042018</v_consulta>\n"
                + "								<v_cve_otorga>UT98002471</v_cve_otorga>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>20000</v_importe_cont>\n"
                + "								<v_nom_otorga>TELCEL</v_nom_otorga>\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>01042018</v_consulta>\n"
                + "								<v_cve_otorga>UT98002491</v_cve_otorga>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>TELCEL</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>22022018</v_consulta>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>02012018</v_consulta>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>SIC</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>06122017</v_consulta>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>02122017</v_consulta>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>01082017</v_consulta>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>29042017</v_consulta>\n"
                + "								<v_cve_respon>J</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>TIENDA COMERCIAL</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>30032017</v_consulta>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "						</consultasReportadas>\n"
                + "						<cuentasReportadas>\n"
                + "							<cuentas>\n"
                + "								<v_antg_h_pag>11012016</v_antg_h_pag>\n"
                + "								<v_ape_cta>18032016</v_ape_cta>\n"
                + "								<v_cred_max>2183</v_cred_max>\n"
                + "								<v_cve_cta>O</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>M</v_cve_frec_pag>\n"
                + "								<v_cve_otorga>UT98000009</v_cve_otorga>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>11052018</v_f_actualiza>\n"
                + "								<v_f_hist_moro_g>31082016</v_f_hist_moro_g>\n"
                + "								<v_h_m_g>02</v_h_m_g>\n"
                + "								<v_hist_pago>111111111111111111111111</v_hist_pago>\n"
                + "								<v_imp_sald_h_g>448</v_imp_sald_h_g>\n"
                + "								<v_lim_cred>1</v_lim_cred>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>1776</v_monto_pago>\n"
                + "								<v_nom_otorga>TELCELMETRO</v_nom_otorga>\n"
                + "								<v_num_cta_act>90076773</v_num_cta_act>\n"
                + "								<v_rec_h_pag>11042018</v_rec_h_pag>\n"
                + "								<v_reporte>11052018</v_reporte>\n"
                + "								<v_saldo_act>0+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "								<v_ultima_compr>21042018</v_ultima_compr>\n"
                + "								<v_ultimo_pago>11052018</v_ultimo_pago>\n"
                + "							</cuentas>\n"
                + "							<cuentas>\n"
                + "								<v_ape_cta>03042018</v_ape_cta>\n"
                + "								<v_cred_max>600</v_cred_max>\n"
                + "								<v_cve_cta>O</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>M</v_cve_frec_pag>\n"
                + "								<v_cve_otorga>UT98000009</v_cve_otorga>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>08052018</v_f_actualiza>\n"
                + "								<v_lim_cred>1</v_lim_cred>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>0</v_monto_pago>\n"
                + "								<v_nom_otorga>TELCELMETRO</v_nom_otorga>\n"
                + "								<v_num_cta_act>92366245</v_num_cta_act>\n"
                + "								<v_reporte>30042018</v_reporte>\n"
                + "								<v_saldo_act>0+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "							</cuentas>\n"
                + "							<cuentas>\n"
                + "								<v_antg_h_pag>02012018</v_antg_h_pag>\n"
                + "								<v_ape_cta>08022018</v_ape_cta>\n"
                + "								<v_cred_max>10328</v_cred_max>\n"
                + "								<v_cve_cta>R</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>Z</v_cve_frec_pag>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>11052018</v_f_actualiza>\n"
                + "								<v_hist_pago>1X1</v_hist_pago>\n"
                + "								<v_lim_cred>10000</v_lim_cred>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>251</v_monto_pago>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "								<v_rec_h_pag>02032018</v_rec_h_pag>\n"
                + "								<v_reporte>30042018</v_reporte>\n"
                + "								<v_saldo_act>10076+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "								<v_ultima_compr>09042018</v_ultima_compr>\n"
                + "								<v_ultimo_pago>30042018</v_ultimo_pago>\n"
                + "							</cuentas>\n"
                + "							<cuentas>\n"
                + "								<v_antg_h_pag>30122017</v_antg_h_pag>\n"
                + "								<v_ape_cta>01122017</v_ape_cta>\n"
                + "								<v_cred_max>7300</v_cred_max>\n"
                + "								<v_cve_cta>I</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>M</v_cve_frec_pag>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>09052018</v_f_actualiza>\n"
                + "								<v_hist_pago>1111</v_hist_pago>\n"
                + "								<v_lim_cred>7300</v_lim_cred>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>168</v_monto_pago>\n"
                + "								<v_n_pagos>120</v_n_pagos>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "								<v_rec_h_pag>30032018</v_rec_h_pag>\n"
                + "								<v_reporte>30042018</v_reporte>\n"
                + "								<v_saldo_act>7089+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "								<v_ultima_compr>01122017</v_ultima_compr>\n"
                + "								<v_ultimo_pago>23042018</v_ultimo_pago>\n"
                + "							</cuentas>\n"
                + "							<cuentas>\n"
                + "								<v_antg_h_pag>03122016</v_antg_h_pag>\n"
                + "								<v_ape_cta>30032017</v_ape_cta>\n"
                + "								<v_cred_max>5489</v_cred_max>\n"
                + "								<v_cve_cta>R</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>Z</v_cve_frec_pag>\n"
                + "								<v_cve_observa />\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>08052018</v_f_actualiza>\n"
                + "								<v_f_hist_moro_g>31032017</v_f_hist_moro_g>\n"
                + "								<v_h_m_g>00</v_h_m_g>\n"
                + "								<v_hist_pago>1111111111111U00</v_hist_pago>\n"
                + "								<v_imp_sald_h_g>0</v_imp_sald_h_g>\n"
                + "								<v_lim_cred>5000</v_lim_cred>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>65</v_monto_pago>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "								<v_rec_h_pag>03032018</v_rec_h_pag>\n"
                + "								<v_reporte>30042018</v_reporte>\n"
                + "								<v_saldo_act>5489+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "								<v_ultima_compr>21042018</v_ultima_compr>\n"
                + "								<v_ultimo_pago>03042018</v_ultimo_pago>\n"
                + "							</cuentas>\n"
                + "							<cuentas>\n"
                + "								<v_antg_h_pag>02012016</v_antg_h_pag>\n"
                + "								<v_ape_cta>09022016</v_ape_cta>\n"
                + "								<v_cierre_cta>29062016</v_cierre_cta>\n"
                + "								<v_cred_max>15000</v_cred_max>\n"
                + "								<v_cve_cta>I</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>K</v_cve_frec_pag>\n"
                + "								<v_cve_observa />\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>04072016</v_f_actualiza>\n"
                + "								<v_hist_pago>11111</v_hist_pago>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>0</v_monto_pago>\n"
                + "								<v_n_pagos>10</v_n_pagos>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "								<v_rec_h_pag>02052016</v_rec_h_pag>\n"
                + "								<v_reporte>30062016</v_reporte>\n"
                + "								<v_saldo_act>0+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "								<v_ultima_compr>09022016</v_ultima_compr>\n"
                + "								<v_ultimo_pago>28062016</v_ultimo_pago>\n"
                + "							</cuentas>\n"
                + "							<cuentas>\n"
                + "								<v_antg_h_pag>04082015</v_antg_h_pag>\n"
                + "								<v_ape_cta>14092015</v_ape_cta>\n"
                + "								<v_cierre_cta>03022016</v_cierre_cta>\n"
                + "								<v_cred_max>10004</v_cred_max>\n"
                + "								<v_cve_cta>I</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>K</v_cve_frec_pag>\n"
                + "								<v_cve_observa />\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>05022016</v_f_actualiza>\n"
                + "								<v_hist_pago>111111</v_hist_pago>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>0</v_monto_pago>\n"
                + "								<v_n_pagos>10</v_n_pagos>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "								<v_rec_h_pag>04012016</v_rec_h_pag>\n"
                + "								<v_reporte>04022016</v_reporte>\n"
                + "								<v_saldo_act>0+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "								<v_ultima_compr>14092015</v_ultima_compr>\n"
                + "								<v_ultimo_pago>02022016</v_ultimo_pago>\n"
                + "							</cuentas>\n"
                + "							<cuentas>\n"
                + "								<v_antg_h_pag>14022015</v_antg_h_pag>\n"
                + "								<v_ape_cta>24042015</v_ape_cta>\n"
                + "								<v_cierre_cta>14092015</v_cierre_cta>\n"
                + "								<v_cred_max>9004</v_cred_max>\n"
                + "								<v_cve_cta>I</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>K</v_cve_frec_pag>\n"
                + "								<v_cve_observa />\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>15092015</v_f_actualiza>\n"
                + "								<v_hist_pago>1111110</v_hist_pago>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>0</v_monto_pago>\n"
                + "								<v_n_pagos>10</v_n_pagos>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "								<v_rec_h_pag>14082015</v_rec_h_pag>\n"
                + "								<v_reporte>14092015</v_reporte>\n"
                + "								<v_saldo_act>0+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "								<v_ultima_compr>24042015</v_ultima_compr>\n"
                + "								<v_ultimo_pago>11092015</v_ultimo_pago>\n"
                + "							</cuentas>\n"
                + "						</cuentasReportadas>\n"
                + "						<direccionesReportadas>\n"
                + "							<direccion>\n"
                + "								<lis_ciudad>CD DE MEXICO</lis_ciudad>\n"
                + "								<lis_cp>10580</lis_cp>\n"
                + "								<lis_direccion1>AV MEXICO</lis_direccion1>\n"
                + "								<lis_estado />\n"
                + "								<lis_tipo_domicilio>H</lis_tipo_domicilio>\n"
                + "								<fechaDeReporteDeLaDireccion>29042017</fechaDeReporteDeLaDireccion>\n"
                + "							</direccion>\n"
                + "							<direccion>\n"
                + "								<lis_ciudad>CD DE MEXICO</lis_ciudad>\n"
                + "								<lis_cp>06000</lis_cp>\n"
                + "								<lis_direccion1>JOSE MORENO</lis_direccion1>\n"
                + "								<lis_estado />\n"
                + "								<lis_tipo_domicilio>H</lis_tipo_domicilio>\n"
                + "								<fechaDeReporteDeLaDireccion>22072016</fechaDeReporteDeLaDireccion>\n"
                + "							</direccion>\n"
                + "							<direccion>\n"
                + "								<lis_colonia_poblacion>BCA SECA</lis_colonia_poblacion>\n"
                + "								<lis_cp>10580</lis_cp>\n"
                + "								<lis_delegacion_municipio>LA MAGDALENA CONTRERAS\n"
                + "								</lis_delegacion_municipio>\n"
                + "								<lis_direccion1>ALDAMA 69</lis_direccion1>\n"
                + "								<lis_direccion2>0</lis_direccion2>\n"
                + "								<lis_estado />\n"
                + "								<lis_num_tel_en_direccion>62362857</lis_num_tel_en_direccion>\n"
                + "								<lis_tipo_domicilio>H</lis_tipo_domicilio>\n"
                + "								<fechaDeReporteDeLaDireccion>18032016</fechaDeReporteDeLaDireccion>\n"
                + "							</direccion>\n"
                + "							<direccion>\n"
                + "								<lis_ciudad>CD DE MEXICO</lis_ciudad>\n"
                + "								<lis_colonia_poblacion>LA MAGDALENA</lis_colonia_poblacion>\n"
                + "								<lis_cp>10910</lis_cp>\n"
                + "								<lis_delegacion_municipio>LA MAGDALENA CONTRERAS\n"
                + "								</lis_delegacion_municipio>\n"
                + "								<lis_direccion1>CARRANZA 130 18</lis_direccion1>\n"
                + "								<lis_estado />\n"
                + "								<lis_num_tel_en_direccion>5527045422</lis_num_tel_en_direccion>\n"
                + "								<lis_tipo_domicilio>H</lis_tipo_domicilio>\n"
                + "								<fechaDeReporteDeLaDireccion>22042015</fechaDeReporteDeLaDireccion>\n"
                + "							</direccion>\n"
                + "						</direccionesReportadas>\n"
                + "						<empleosReportados>\n"
                + "							<empleo>\n"
                + "								<v_num_tel>5546848564</v_num_tel>\n"
                + "								<v_patron_rz>PROFESIONISTA INDEPENDIENTE</v_patron_rz>\n"
                + "							</empleo>\n"
                + "							<empleo>\n"
                + "								<v_patron_rz>TRABAJADOR INDEPENDIENTE</v_patron_rz>\n"
                + "							</empleo>\n"
                + "						</empleosReportados>\n"
                + "						<encabezadoResponseINTL>\n"
                + "							<lis_referencia_operador>CCS18090411535592526\n"
                + "							</lis_referencia_operador>\n"
                + "							<v_buro>0000</v_buro>\n"
                + "							<v_cve_otorga>ZM98001006</v_cve_otorga>\n"
                + "							<v_cve_retorno_p>1</v_cve_retorno_p>\n"
                + "							<v_cve_retorno_s>0</v_cve_retorno_s>\n"
                + "							<v_pais />\n"
                + "							<v_version>11</v_version>\n"
                + "						</encabezadoResponseINTL>\n"
                + "						<fin>\n"
                + "							<v_chr_fin>0102</v_chr_fin>\n"
                + "							<v_ctrl_consul>1001100031</v_ctrl_consul>\n"
                + "							<v_long>03005</v_long>\n"
                + "						</fin>\n"
                + "						<nombre>\n"
                + "							<lv_ape_mat>GONZALEZ</lv_ape_mat>\n"
                + "							<lv_ape_pat>SANCHEZ</lv_ape_pat>\n"
                + "							<lv_prim_nom>GIL</lv_prim_nom>\n"
                + "							<lv_rfc>SAGG720228P95</lv_rfc>\n"
                + "						</nombre>\n"
                + "						<reportesRealizados>\n"
                + "							<resumenReporte>\n"
                + "								<v_declara>N</v_declara>\n"
                + "								<v_ingre_bd>22052018</v_ingre_bd>\n"
                + "								<v_mop_00>00</v_mop_00>\n"
                + "								<v_mop_01>08</v_mop_01>\n"
                + "								<v_mop_02>00</v_mop_02>\n"
                + "								<v_mop_03>00</v_mop_03>\n"
                + "								<v_mop_04>00</v_mop_04>\n"
                + "								<v_mop_05>00</v_mop_05>\n"
                + "								<v_mop_06>00</v_mop_06>\n"
                + "								<v_mop_07>00</v_mop_07>\n"
                + "								<v_mop_96>00</v_mop_96>\n"
                + "								<v_mop_97>00</v_mop_97>\n"
                + "								<v_mop_99>00</v_mop_99>\n"
                + "								<v_mop_ur>00</v_mop_ur>\n"
                + "								<v_msg_allert>NNNNNY</v_msg_allert>\n"
                + "								<v_n_cta_cerr>0003</v_n_cta_cerr>\n"
                + "								<v_n_cta_disp>00</v_n_cta_disp>\n"
                + "								<v_n_cta_neg>0000</v_n_cta_neg>\n"
                + "								<v_n_cta_ra>0004</v_n_cta_ra>\n"
                + "								<v_n_ctas_mop>0002</v_n_ctas_mop>\n"
                + "								<v_n_cuenta>0008</v_n_cuenta>\n"
                + "								<v_n_pago_f>0004</v_n_pago_f>\n"
                + "								<v_n_sol_6_mes>03</v_n_sol_6_mes>\n"
                + "								<v_n_sol_cc>00</v_n_sol_cc>\n"
                + "								<v_n_t_cta_des_cob>00</v_n_t_cta_des_cob>\n"
                + "								<v_n_t_repo>10</v_n_t_repo>\n"
                + "								<v_n_t_repo_rec>04042018</v_n_t_repo_rec>\n"
                + "								<v_open_cc>00000000</v_open_cc>\n"
                + "								<v_open_cta_ant>24042015</v_open_cta_ant>\n"
                + "								<v_open_cta_rec>03042018</v_open_cta_rec>\n"
                + "								<v_sol_cc>00000000</v_sol_cc>\n"
                + "								<v_t_cred_max_fh>7300</v_t_cred_max_fh>\n"
                + "								<v_t_cta_cred_max>18600</v_t_cta_cred_max>\n"
                + "								<v_t_l_cred_max>15002</v_t_l_cred_max>\n"
                + "								<v_t_pagos>2092</v_t_pagos>\n"
                + "								<v_t_pagos_fh>168</v_t_pagos_fh>\n"
                + "								<v_t_porcen_lc>103</v_t_porcen_lc>\n"
                + "								<v_t_sald_max>15565+</v_t_sald_max>\n"
                + "								<v_t_sald_ven>0</v_t_sald_ven>\n"
                + "								<v_t_saldo_fh>7089+</v_t_saldo_fh>\n"
                + "								<v_t_saldo_v_fh>0</v_t_saldo_v_fh>\n"
                + "								<v_u_dirr>N</v_u_dirr>\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "							</resumenReporte>\n"
                + "						</reportesRealizados>\n"
                + "						<scoresReportados>\n"
                + "							<score>\n"
                + "								<v_cod_score>007</v_cod_score>\n"
                + "								<v_code_razon1>15</v_code_razon1>\n"
                + "								<v_code_razon2>09</v_code_razon2>\n"
                + "								<v_nom_score>BC SCORE</v_nom_score>\n"
                + "								<v_val_score>0681</v_val_score>\n"
                + "							</score>\n"
                + "							<score>\n"
                + "								<v_cod_score>004</v_cod_score>\n"
                + "								<v_code_razon1>166</v_code_razon1>\n"
                + "								<v_code_razon2>200</v_code_razon2>\n"
                + "								<v_code_razon3>100</v_code_razon3>\n"
                + "								<v_nom_score>BC SCORE</v_nom_score>\n"
                + "								<v_val_score>0005</v_val_score>\n"
                + "							</score>\n"
                + "						</scoresReportados>\n"
                + "					</reporteDeCredito>\n"
                + "				</autenticado>\n"
                + "				<header>\n"
                + "					<folio>CCS18090411535592526</folio>\n"
                + "					<horaRespuestaSalida>04092018115332</horaRespuestaSalida>\n"
                + "				</header>\n"
                + "			</responseProvider>\n"
                + "			<tipoReporte />\n"
                + "		</value>\n"
                + "	</respuesta>\n"
                + "</reporteBcIccWSBean>";

        String telcoIccIn = "<reporteBcIccWSBean>\n"
                + "	<controlData>\n"
                + "		<messageUUID>BCSERVICES-PF-LOCAL-0001</messageUUID>\n"
                + "		<requestDate>2018-09-04T11:49:01.275-05:00</requestDate>\n"
                + "		<sendBy>CLIENT</sendBy>\n"
                + "		<version>1</version>\n"
                + "	</controlData>\n"
                + "	<peticion>\n"
                + "		<solicitud>\n"
                + "			<header>\n"
                + "				<folio>CCS18090411490192525</folio>\n"
                + "				<historico>0</historico>\n"
                + "				<horaEntrada>20180904114901</horaEntrada>\n"
                + "				<idSistema>DEUR</idSistema>\n"
                + "				<ip>191.9.6.18</ip>\n"
                + "				<usuario>DEUR</usuario>\n"
                + "			</header>\n"
                + "			<segmentos>\n"
                + "				<autenticacion>\n"
                + "					<lis_cred_hipoteca_banco>F</lis_cred_hipoteca_banco>\n"
                + "					<lis_credito_automotriz>F</lis_credito_automotriz>\n"
                + "					<lis_cuenta_con_tc>V</lis_cuenta_con_tc>\n"
                + "					<lis_referencia_operador>CCS1809041149019I00002525</lis_referencia_operador>\n"
                + "					<lis_tipo_reporte>RCN</lis_tipo_reporte>\n"
                + "					<lis_tipo_salida>1</lis_tipo_salida>\n"
                + "					<lis_ultimos_digitos>6165</lis_ultimos_digitos>\n"
                + "				</autenticacion>\n"
                + "				<direccion>\n"
                + "					<lis_ciudad>LA MAGDALENA CONTRERAS</lis_ciudad>\n"
                + "					<lis_cp>10580</lis_cp>\n"
                + "					<lis_delegacion_municipio>LA MAGDALENA CONTRERAS</lis_delegacion_municipio>\n"
                + "					<lis_direccion1>ALDAMA 68</lis_direccion1>\n"
                + "					<lis_estado />\n"
                + "				</direccion>\n"
                + "				<encabezadoINTL>\n"
                + "					<adm_intl_idioma>SP</adm_intl_idioma>\n"
                + "					<adm_intl_imp_contrato>000000000</adm_intl_imp_contrato>\n"
                + "					<adm_intl_tipo_contrato />\n"
                + "					<adm_intl_tipo_cta>I</adm_intl_tipo_cta>\n"
                + "					<adm_intl_unidadmonetaria>MX</adm_intl_unidadmonetaria>\n"
                + "					<lis_referencia_operador>CCS1809041149019I00002525</lis_referencia_operador>\n"
                + "					<ls_pass>hEXSmXfR</ls_pass>\n"
                + "					<ls_usr>ZM98001006</ls_usr>\n"
                + "					<productoRequerido />\n"
                + "				</encabezadoINTL>\n"
                + "				<nombre>\n"
                + "					<lv_ape_mat>GONZALEZ</lv_ape_mat>\n"
                + "					<lv_ape_pat>SANCHEZ</lv_ape_pat>\n"
                + "					<lv_prim_nom>GIL</lv_prim_nom>\n"
                + "					<lv_rfc>SAGG720228000</lv_rfc>\n"
                + "				</nombre>\n"
                + "			</segmentos>\n"
                + "		</solicitud>\n"
                + "		<tipoReporte />\n"
                + "		<tipoSolicitud>repoBC</tipoSolicitud>\n"
                + "	</peticion>\n"
                + "	<controlData2 />\n"
                + "	<detailResponse />\n"
                + "	<respuesta />\n"
                + "</reporteBcIccWSBean>";

        String telcoIccOut = "<reporteBcIccWSBean>\n"
                + "	<controlData>\n"
                + "		<messageUUID>BCSERVICES-PF-LOCAL-0001</messageUUID>\n"
                + "		<requestDate>2018-09-04T11:49:01.275-05:00</requestDate>\n"
                + "		<sendBy>CLIENT</sendBy>\n"
                + "		<version>1</version>\n"
                + "	</controlData>\n"
                + "	<peticion>\n"
                + "		<solicitud>\n"
                + "			<header>\n"
                + "				<folio>CCS18090411490192525</folio>\n"
                + "				<historico>0</historico>\n"
                + "				<horaEntrada>20180904114901</horaEntrada>\n"
                + "				<idSistema>DEUR</idSistema>\n"
                + "				<ip>191.9.6.18</ip>\n"
                + "				<usuario>DEUR</usuario>\n"
                + "			</header>\n"
                + "			<segmentos>\n"
                + "				<autenticacion>\n"
                + "					<lis_cred_hipoteca_banco>F</lis_cred_hipoteca_banco>\n"
                + "					<lis_credito_automotriz>F</lis_credito_automotriz>\n"
                + "					<lis_cuenta_con_tc>V</lis_cuenta_con_tc>\n"
                + "					<lis_referencia_operador>CCS1809041149019I00002525\n"
                + "					</lis_referencia_operador>\n"
                + "					<lis_tipo_reporte>RCN</lis_tipo_reporte>\n"
                + "					<lis_tipo_salida>1</lis_tipo_salida>\n"
                + "					<lis_ultimos_digitos>6165</lis_ultimos_digitos>\n"
                + "				</autenticacion>\n"
                + "				<direccion>\n"
                + "					<lis_ciudad>LA MAGDALENA CONTRERAS</lis_ciudad>\n"
                + "					<lis_cp>10580</lis_cp>\n"
                + "					<lis_delegacion_municipio>LA MAGDALENA CONTRERAS\n"
                + "					</lis_delegacion_municipio>\n"
                + "					<lis_direccion1>ALDAMA 68</lis_direccion1>\n"
                + "					<lis_estado />\n"
                + "				</direccion>\n"
                + "				<encabezadoINTL>\n"
                + "					<adm_intl_idioma>SP</adm_intl_idioma>\n"
                + "					<adm_intl_imp_contrato>000000000</adm_intl_imp_contrato>\n"
                + "					<adm_intl_tipo_contrato />\n"
                + "					<adm_intl_tipo_cta>I</adm_intl_tipo_cta>\n"
                + "					<adm_intl_unidadmonetaria>MX</adm_intl_unidadmonetaria>\n"
                + "					<lis_referencia_operador>CCS1809041149019I00002525\n"
                + "					</lis_referencia_operador>\n"
                + "					<ls_pass>hEXSmXfR</ls_pass>\n"
                + "					<ls_usr>ZM98001006</ls_usr>\n"
                + "					<productoRequerido />\n"
                + "				</encabezadoINTL>\n"
                + "				<nombre>\n"
                + "					<lv_ape_mat>GONZALEZ</lv_ape_mat>\n"
                + "					<lv_ape_pat>SANCHEZ</lv_ape_pat>\n"
                + "					<lv_prim_nom>GIL</lv_prim_nom>\n"
                + "					<lv_rfc>SAGG720228000</lv_rfc>\n"
                + "				</nombre>\n"
                + "			</segmentos>\n"
                + "		</solicitud>\n"
                + "		<tipoReporte />\n"
                + "		<tipoSolicitud>repoBC</tipoSolicitud>\n"
                + "	</peticion>\n"
                + "	<controlData2>\n"
                + "		<value>\n"
                + "			<latency>10796</latency>\n"
                + "			<messageUUID>BCSERVICES-PF-LOCAL-0001</messageUUID>\n"
                + "			<responseDate>2018-09-04T11:48:14.451</responseDate>\n"
                + "			<sendBy>ESB</sendBy>\n"
                + "			<version>1</version>\n"
                + "		</value>\n"
                + "	</controlData2>\n"
                + "	<detailResponse>\n"
                + "		<value>\n"
                + "			<actor>IdProviderServices_getIdProvBCSC</actor>\n"
                + "			<businessMeaning>REPORTE EXITOSO</businessMeaning>\n"
                + "			<code>0</code>\n"
                + "			<description>RESPUESTA EXITOSA</description>\n"
                + "			<severityLevel>1</severityLevel>\n"
                + "		</value>\n"
                + "	</detailResponse>\n"
                + "	<respuesta>\n"
                + "		<value>\n"
                + "			<responseProvider>\n"
                + "				<autenticado>\n"
                + "					<reporteDeCredito>\n"
                + "						<consultasReportadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>04092018</v_consulta>\n"
                + "								<v_cve_otorga>ZM98001006</v_cve_otorga>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>TELCEL</v_nom_otorga>\n"
                + "							</consultasEfectuadas>						\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>02012018</v_consulta>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>SIC</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "							<consultasEfectuadas>\n"
                + "								<v_consulta>30032017</v_consulta>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_cve_t_contr />\n"
                + "								<v_importe_cont>0</v_importe_cont>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "							</consultasEfectuadas>\n"
                + "						</consultasReportadas>\n"
                + "						<cuentasReportadas>\n"
                + "							<cuentas>\n"
                + "								<v_ape_cta>03042018</v_ape_cta>\n"
                + "								<v_cred_max>600</v_cred_max>\n"
                + "								<v_cve_cta>O</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>M</v_cve_frec_pag>\n"
                + "								<v_cve_otorga>UT98000009</v_cve_otorga>\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>08052018</v_f_actualiza>\n"
                + "								<v_lim_cred>1</v_lim_cred>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>0</v_monto_pago>\n"
                + "								<v_nom_otorga>TELCELMETRO</v_nom_otorga>\n"
                + "								<v_num_cta_act>92366245</v_num_cta_act>\n"
                + "								<v_reporte>30042018</v_reporte>\n"
                + "								<v_saldo_act>0+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "							</cuentas>\n"
                + "							<cuentas>\n"
                + "								<v_antg_h_pag>03122016</v_antg_h_pag>\n"
                + "								<v_ape_cta>30032017</v_ape_cta>\n"
                + "								<v_cred_max>5489</v_cred_max>\n"
                + "								<v_cve_cta>R</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>Z</v_cve_frec_pag>\n"
                + "								<v_cve_observa />\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>08052018</v_f_actualiza>\n"
                + "								<v_f_hist_moro_g>31032017</v_f_hist_moro_g>\n"
                + "								<v_h_m_g>00</v_h_m_g>\n"
                + "								<v_hist_pago>1111111111111U00</v_hist_pago>\n"
                + "								<v_imp_sald_h_g>0</v_imp_sald_h_g>\n"
                + "								<v_lim_cred>5000</v_lim_cred>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>65</v_monto_pago>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "								<v_rec_h_pag>03032018</v_rec_h_pag>\n"
                + "								<v_reporte>30042018</v_reporte>\n"
                + "								<v_saldo_act>5489+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "								<v_ultima_compr>21042018</v_ultima_compr>\n"
                + "								<v_ultimo_pago>03042018</v_ultimo_pago>\n"
                + "							</cuentas>\n"
                + "							<cuentas>\n"
                + "								<v_antg_h_pag>02012016</v_antg_h_pag>\n"
                + "								<v_ape_cta>09022016</v_ape_cta>\n"
                + "								<v_cierre_cta>29062016</v_cierre_cta>\n"
                + "								<v_cred_max>15000</v_cred_max>\n"
                + "								<v_cve_cta>I</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>K</v_cve_frec_pag>\n"
                + "								<v_cve_observa />\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>04072016</v_f_actualiza>\n"
                + "								<v_hist_pago>11111</v_hist_pago>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>0</v_monto_pago>\n"
                + "								<v_n_pagos>10</v_n_pagos>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "								<v_rec_h_pag>02052016</v_rec_h_pag>\n"
                + "								<v_reporte>30062016</v_reporte>\n"
                + "								<v_saldo_act>0+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "								<v_ultima_compr>09022016</v_ultima_compr>\n"
                + "								<v_ultimo_pago>28062016</v_ultimo_pago>\n"
                + "							</cuentas>\n"
                + "							<cuentas>\n"
                + "								<v_antg_h_pag>04082015</v_antg_h_pag>\n"
                + "								<v_ape_cta>14092015</v_ape_cta>\n"
                + "								<v_cierre_cta>03022016</v_cierre_cta>\n"
                + "								<v_cred_max>10004</v_cred_max>\n"
                + "								<v_cve_cta>I</v_cve_cta>\n"
                + "								<v_cve_for_pag>01</v_cve_for_pag>\n"
                + "								<v_cve_frec_pag>K</v_cve_frec_pag>\n"
                + "								<v_cve_observa />\n"
                + "								<v_cve_respon>I</v_cve_respon>\n"
                + "								<v_f_actualiza>05022016</v_f_actualiza>\n"
                + "								<v_hist_pago>111111</v_hist_pago>\n"
                + "								<v_modo_repor>A</v_modo_repor>\n"
                + "								<v_monto_pago>0</v_monto_pago>\n"
                + "								<v_n_pagos>10</v_n_pagos>\n"
                + "								<v_nom_otorga>BANCO</v_nom_otorga>\n"
                + "								<v_rec_h_pag>04012016</v_rec_h_pag>\n"
                + "								<v_reporte>04022016</v_reporte>\n"
                + "								<v_saldo_act>0+</v_saldo_act>\n"
                + "								<v_saldo_ven>0</v_saldo_ven>\n"
                + "								<v_t_contrato />\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "								<v_ultima_compr>14092015</v_ultima_compr>\n"
                + "								<v_ultimo_pago>02022016</v_ultimo_pago>\n"
                + "							</cuentas>\n"
                + "						</cuentasReportadas>\n"
                + "						<direccionesReportadas>\n"
                + "							<direccion>\n"
                + "								<lis_colonia_poblacion>BCA SECA</lis_colonia_poblacion>\n"
                + "								<lis_cp>10580</lis_cp>\n"
                + "								<lis_delegacion_municipio>LA MAGDALENA CONTRERAS\n"
                + "								</lis_delegacion_municipio>\n"
                + "								<lis_direccion1>ALDAMA 69</lis_direccion1>\n"
                + "								<lis_direccion2>0</lis_direccion2>\n"
                + "								<lis_estado />\n"
                + "								<lis_num_tel_en_direccion>62362857</lis_num_tel_en_direccion>\n"
                + "								<lis_tipo_domicilio>H</lis_tipo_domicilio>\n"
                + "								<fechaDeReporteDeLaDireccion>18032016</fechaDeReporteDeLaDireccion>\n"
                + "							</direccion>\n"
                + "							<direccion>\n"
                + "								<lis_ciudad>CD DE MEXICO</lis_ciudad>\n"
                + "								<lis_colonia_poblacion>LA MAGDALENA</lis_colonia_poblacion>\n"
                + "								<lis_cp>10910</lis_cp>\n"
                + "								<lis_delegacion_municipio>LA MAGDALENA CONTRERAS\n"
                + "								</lis_delegacion_municipio>\n"
                + "								<lis_direccion1>CARRANZA 130 18</lis_direccion1>\n"
                + "								<lis_estado />\n"
                + "								<lis_num_tel_en_direccion>5527045422</lis_num_tel_en_direccion>\n"
                + "								<lis_tipo_domicilio>H</lis_tipo_domicilio>\n"
                + "								<fechaDeReporteDeLaDireccion>22042015</fechaDeReporteDeLaDireccion>\n"
                + "							</direccion>\n"
                + "						</direccionesReportadas>\n"
                + "						<empleosReportados>\n"
                + "							<empleo>\n"
                + "								<v_num_tel>5546848564</v_num_tel>\n"
                + "								<v_patron_rz>PROFESIONISTA INDEPENDIENTE</v_patron_rz>\n"
                + "							</empleo>\n"
                + "							<empleo>\n"
                + "								<v_patron_rz>TRABAJADOR INDEPENDIENTE</v_patron_rz>\n"
                + "							</empleo>\n"
                + "						</empleosReportados>\n"
                + "						<encabezadoResponseINTL>\n"
                + "							<lis_referencia_operador>CCS18090411490192525\n"
                + "							</lis_referencia_operador>\n"
                + "							<v_buro>0000</v_buro>\n"
                + "							<v_cve_otorga>ZM98001006</v_cve_otorga>\n"
                + "							<v_cve_retorno_p>1</v_cve_retorno_p>\n"
                + "							<v_cve_retorno_s>0</v_cve_retorno_s>\n"
                + "							<v_pais />\n"
                + "							<v_version>11</v_version>\n"
                + "						</encabezadoResponseINTL>\n"
                + "						<fin>\n"
                + "							<v_chr_fin>0102</v_chr_fin>\n"
                + "							<v_ctrl_consul>1001100001</v_ctrl_consul>\n"
                + "							<v_long>03005</v_long>\n"
                + "						</fin>\n"
                + "						<nombre>\n"
                + "							<lv_ape_mat>GONZALEZ</lv_ape_mat>\n"
                + "							<lv_ape_pat>SANCHEZ</lv_ape_pat>\n"
                + "							<lv_prim_nom>GIL</lv_prim_nom>\n"
                + "							<lv_rfc>SAGG720228P95</lv_rfc>\n"
                + "						</nombre>\n"
                + "						<reportesRealizados>\n"
                + "							<resumenReporte>\n"
                + "								<v_declara>N</v_declara>\n"
                + "								<v_ingre_bd>22052018</v_ingre_bd>\n"
                + "								<v_mop_00>00</v_mop_00>\n"
                + "								<v_mop_01>08</v_mop_01>\n"
                + "								<v_mop_02>00</v_mop_02>\n"
                + "								<v_mop_03>00</v_mop_03>\n"
                + "								<v_mop_04>00</v_mop_04>\n"
                + "								<v_mop_05>00</v_mop_05>\n"
                + "								<v_mop_06>00</v_mop_06>\n"
                + "								<v_mop_07>00</v_mop_07>\n"
                + "								<v_mop_96>00</v_mop_96>\n"
                + "								<v_mop_97>00</v_mop_97>\n"
                + "								<v_mop_99>00</v_mop_99>\n"
                + "								<v_mop_ur>00</v_mop_ur>\n"
                + "								<v_msg_allert>NNNNNY</v_msg_allert>\n"
                + "								<v_n_cta_cerr>0003</v_n_cta_cerr>\n"
                + "								<v_n_cta_disp>00</v_n_cta_disp>\n"
                + "								<v_n_cta_neg>0000</v_n_cta_neg>\n"
                + "								<v_n_cta_ra>0004</v_n_cta_ra>\n"
                + "								<v_n_ctas_mop>0002</v_n_ctas_mop>\n"
                + "								<v_n_cuenta>0008</v_n_cuenta>\n"
                + "								<v_n_pago_f>0004</v_n_pago_f>\n"
                + "								<v_n_sol_6_mes>03</v_n_sol_6_mes>\n"
                + "								<v_n_sol_cc>00</v_n_sol_cc>\n"
                + "								<v_n_t_cta_des_cob>00</v_n_t_cta_des_cob>\n"
                + "								<v_n_t_repo>10</v_n_t_repo>\n"
                + "								<v_n_t_repo_rec>04042018</v_n_t_repo_rec>\n"
                + "								<v_open_cc>00000000</v_open_cc>\n"
                + "								<v_open_cta_ant>24042015</v_open_cta_ant>\n"
                + "								<v_open_cta_rec>03042018</v_open_cta_rec>\n"
                + "								<v_sol_cc>00000000</v_sol_cc>\n"
                + "								<v_t_cred_max_fh>7300</v_t_cred_max_fh>\n"
                + "								<v_t_cta_cred_max>18600</v_t_cta_cred_max>\n"
                + "								<v_t_l_cred_max>15002</v_t_l_cred_max>\n"
                + "								<v_t_pagos>2092</v_t_pagos>\n"
                + "								<v_t_pagos_fh>168</v_t_pagos_fh>\n"
                + "								<v_t_porcen_lc>103</v_t_porcen_lc>\n"
                + "								<v_t_sald_max>15565+</v_t_sald_max>\n"
                + "								<v_t_sald_ven>0</v_t_sald_ven>\n"
                + "								<v_t_saldo_fh>7089+</v_t_saldo_fh>\n"
                + "								<v_t_saldo_v_fh>0</v_t_saldo_v_fh>\n"
                + "								<v_u_dirr>N</v_u_dirr>\n"
                + "								<v_u_monetaria>MX</v_u_monetaria>\n"
                + "							</resumenReporte>\n"
                + "						</reportesRealizados>\n"
                + "						<scoresReportados>  -- No se encuentra \n"
                + "							<score>\n"
                + "								<v_cod_score>004</v_cod_score>\n"
                + "								<v_code_razon1>166</v_code_razon1>\n"
                + "								<v_code_razon2>200</v_code_razon2>\n"
                + "								<v_code_razon3>100</v_code_razon3>\n"
                + "								<v_nom_score>BC SCORE</v_nom_score>\n"
                + "								<v_val_score>0005</v_val_score>\n"
                + "							</score>\n"
                + "							<score>\n"
                + "								<v_cod_score>011</v_cod_score>\n"
                + "								<v_code_razon1>55</v_code_razon1>\n"
                + "								<v_code_razon2>56</v_code_razon2>\n"
                + "								<v_nom_score>BC SCORE</v_nom_score>\n"
                + "								<v_val_score>0682</v_val_score>\n"
                + "							</score>\n"
                + "						</scoresReportados>\n"
                + "					</reporteDeCredito>\n"
                + "				</autenticado>\n"
                + "				<header>\n"
                + "					<folio>CCS18090411490192525</folio>\n"
                + "					<horaRespuestaSalida>04092018114901</horaRespuestaSalida>\n"
                + "				</header>\n"
                + "			</responseProvider>\n"
                + "			<tipoReporte />\n"
                + "		</value>\n"
                + "	</respuesta>\n"
                + "</reporteBcIccWSBean>";
        
        
    }
}
